FROM  barciewicz/sampler_new:latest

COPY requirements.txt .

RUN pip install -r requirements.txt

# https://github.com/ytdl-org/youtube-dl/issues/31530
RUN pip install --upgrade --force-reinstall "git+https://github.com/ytdl-org/youtube-dl.git"

COPY . .

RUN python manage.py makemigrations
RUN python manage.py migrate

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]