# Generated by Django 2.0.3 on 2019-12-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampler.Sample')),
            ],
        ),
    ]
