# Generated by Django 2.0.3 on 2019-12-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampler', '0003_auto_20191231_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='sample',
        ),
        migrations.AlterField(
            model_name='sample',
            name='audio',
            field=models.FileField(upload_to='samples'),
        ),
        migrations.DeleteModel(
            name='Slice',
        ),
    ]
