# Generated by Django 2.0.3 on 2020-01-29 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampler', '0004_auto_20191231_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 29, 20, 8, 27, 424635, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
